### ISSUE TITLE
Fix affiliations

### ISSUE THREAD

**Issue by korbinib** [elixir-oslo/biomeddata#14]
Add 

- [x] affiliations.yml
- [x] RI logos
- [x] affiliations in cheat sheets

**Comment by Nazeeefa** [comment]
We discussed to use: 'Research Infrastructure: <full name (acronym)> logo" instead of affiliation.

**Comment by korbinib** [comment]
'Affiliation' would have to be changed in the theme. Not sure if we want to fork it just because of that.

**Comment by korbinib** [comment]
close for now, might revisit
