### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-oslo/biomeddata#23]
`<span class="input-group-text" id="search-label"><i class="fa-solid fa-magnifying-glass"></i></span><input type="search" id="search-input" class="search-input form-control" tabindex="0" placeholder="Search Life Science Data Management LookUp" aria-label="Search Life Science Data Management LookUp" autocomplete="off">
`

replace _Search Life Science Data Management LookUp_ with 'Search using a keyword' or 'Search the lookup with a keyword'

**Comment by korbinib** [comment]
closed by https://github.com/elixir-oslo/biomeddata/commit/8009f770948d1d49baeb2b8c3dcf5f55157dec96
